/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Wed Sep 21 18:52:02 2011
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QStackedWidget>
#include <QtGui/QStatusBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page_5;
    QPushButton *pushButton_7;
    QPushButton *pushButton_9;
    QPushButton *pushButton_8;
    QPushButton *pushButton_6;
    QPushButton *pushButton_5;
    QPushButton *pushButton_10;
    QWidget *page;
    QLabel *label;
    QLineEdit *lnNombreBD;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lnVersion;
    QLineEdit *lnContra;
    QSpinBox *spinCantidad;
    QPushButton *btnCrear;
    QPushButton *btnCrear_2;
    QWidget *page_2;
    QLabel *label_6;
    QLineEdit *lnNombreTabla;
    QPushButton *pushButton;
    QLabel *label_8;
    QSpinBox *spinBox;
    QWidget *page_3;
    QLabel *label_7;
    QLineEdit *lnNombreCampo;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_13;
    QSpinBox *spinSize;
    QCheckBox *chkNull;
    QCheckBox *chkPK;
    QLineEdit *lnDefault;
    QPushButton *pushButton_2;
    QListWidget *listWidget;
    QSpinBox *spinTipo;
    QPushButton *pushButton_3;
    QLabel *label_11;
    QPushButton *btnCrear_3;
    QWidget *page_4;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLineEdit *lineEdit1;
    QLineEdit *lineEdit2;
    QLineEdit *lineEdit3;
    QLineEdit *lineEdit4;
    QLabel *label_27;
    QPushButton *pushButton_4;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QCheckBox *checkBox_6;
    QCheckBox *checkBox_7;
    QPushButton *btnCrear_4;
    QLineEdit *lineEdit_5;
    QLabel *label_41;
    QLineEdit *lineEdit5;
    QLineEdit *lineEditMD;
    QLabel *label_43;
    QWidget *page_6;
    QPushButton *btnCrear_5;
    QPushButton *pushButton_11;
    QLabel *label_33;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit3_;
    QLabel *label_34;
    QCheckBox *checkBox_8;
    QCheckBox *checkBox_9;
    QLineEdit *lineEdit2_;
    QLineEdit *lineEdit1_;
    QCheckBox *checkBox_10;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *lineEdit4_;
    QCheckBox *checkBox_11;
    QLabel *label_38;
    QCheckBox *checkBox_12;
    QLineEdit *lineEdit_11;
    QLabel *label_39;
    QLabel *label_40;
    QLineEdit *lineEdit_12;
    QLabel *label_42;
    QLineEdit *lineEdit5_;
    QWidget *page_7;
    QLabel *label_91;
    QLineEdit *_lineEdit2;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QPushButton *btnCrear_16;
    QLabel *label_95;
    QLineEdit *_lineEdit4;
    QCheckBox *checkBox_39;
    QLabel *label_96;
    QCheckBox *checkBox_40;
    QLabel *label_97;
    QLineEdit *_lineEdit1;
    QLineEdit *lineEdit_46;
    QLineEdit *_lineEdit3;
    QPushButton *pushButton_34;
    QCheckBox *checkBox_38;
    QLabel *label_98;
    QCheckBox *checkBox_41;
    QLineEdit *lineEdit_45;
    QCheckBox *checkBox_42;
    QLineEdit *_lineEdit5;
    QLineEdit *lineEdit_13;
    QLabel *label_44;
    QWidget *page_20;
    QLineEdit *lineEdit_105;
    QLabel *label_205;
    QLineEdit *lineEdit_106;
    QLabel *label_206;
    QLabel *label_207;
    QPushButton *btnCrear_35;
    QPushButton *pushButton_71;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(784, 536);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 781, 481));
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        pushButton_7 = new QPushButton(page_5);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(70, 180, 151, 27));
        pushButton_9 = new QPushButton(page_5);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(70, 260, 151, 27));
        pushButton_8 = new QPushButton(page_5);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(70, 220, 151, 27));
        pushButton_6 = new QPushButton(page_5);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(70, 140, 151, 27));
        pushButton_5 = new QPushButton(page_5);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(70, 100, 151, 27));
        pushButton_10 = new QPushButton(page_5);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(70, 60, 151, 27));
        stackedWidget->addWidget(page_5);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label = new QLabel(page);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(40, 50, 141, 17));
        lnNombreBD = new QLineEdit(page);
        lnNombreBD->setObjectName(QString::fromUtf8("lnNombreBD"));
        lnNombreBD->setGeometry(QRect(160, 100, 113, 27));
        label_2 = new QLabel(page);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 110, 91, 17));
        label_3 = new QLabel(page);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 150, 81, 17));
        label_4 = new QLabel(page);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 190, 111, 17));
        label_5 = new QLabel(page);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 230, 131, 17));
        lnVersion = new QLineEdit(page);
        lnVersion->setObjectName(QString::fromUtf8("lnVersion"));
        lnVersion->setGeometry(QRect(160, 140, 113, 27));
        lnContra = new QLineEdit(page);
        lnContra->setObjectName(QString::fromUtf8("lnContra"));
        lnContra->setGeometry(QRect(160, 180, 113, 27));
        spinCantidad = new QSpinBox(page);
        spinCantidad->setObjectName(QString::fromUtf8("spinCantidad"));
        spinCantidad->setGeometry(QRect(160, 220, 111, 27));
        btnCrear = new QPushButton(page);
        btnCrear->setObjectName(QString::fromUtf8("btnCrear"));
        btnCrear->setGeometry(QRect(140, 280, 131, 27));
        btnCrear_2 = new QPushButton(page);
        btnCrear_2->setObjectName(QString::fromUtf8("btnCrear_2"));
        btnCrear_2->setGeometry(QRect(10, 320, 71, 27));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_6 = new QLabel(page_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 70, 111, 17));
        lnNombreTabla = new QLineEdit(page_2);
        lnNombreTabla->setObjectName(QString::fromUtf8("lnNombreTabla"));
        lnNombreTabla->setGeometry(QRect(150, 60, 113, 27));
        pushButton = new QPushButton(page_2);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(150, 150, 111, 27));
        label_8 = new QLabel(page_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 110, 121, 17));
        spinBox = new QSpinBox(page_2);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(150, 100, 111, 27));
        spinBox->setMinimum(1);
        spinBox->setMaximum(16);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_7 = new QLabel(page_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 100, 111, 17));
        lnNombreCampo = new QLineEdit(page_3);
        lnNombreCampo->setObjectName(QString::fromUtf8("lnNombreCampo"));
        lnNombreCampo->setGeometry(QRect(170, 140, 113, 27));
        label_9 = new QLabel(page_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 150, 111, 17));
        label_10 = new QLabel(page_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 190, 151, 17));
        label_13 = new QLabel(page_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(20, 230, 151, 20));
        spinSize = new QSpinBox(page_3);
        spinSize->setObjectName(QString::fromUtf8("spinSize"));
        spinSize->setGeometry(QRect(170, 180, 111, 27));
        spinSize->setMinimum(1);
        spinSize->setMaximum(255);
        chkNull = new QCheckBox(page_3);
        chkNull->setObjectName(QString::fromUtf8("chkNull"));
        chkNull->setGeometry(QRect(20, 270, 97, 22));
        chkPK = new QCheckBox(page_3);
        chkPK->setObjectName(QString::fromUtf8("chkPK"));
        chkPK->setGeometry(QRect(20, 310, 97, 22));
        lnDefault = new QLineEdit(page_3);
        lnDefault->setObjectName(QString::fromUtf8("lnDefault"));
        lnDefault->setGeometry(QRect(170, 220, 113, 27));
        pushButton_2 = new QPushButton(page_3);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(170, 340, 97, 27));
        listWidget = new QListWidget(page_3);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(340, 90, 161, 281));
        spinTipo = new QSpinBox(page_3);
        spinTipo->setObjectName(QString::fromUtf8("spinTipo"));
        spinTipo->setGeometry(QRect(170, 100, 111, 27));
        spinTipo->setMinimum(1);
        spinTipo->setMaximum(5);
        pushButton_3 = new QPushButton(page_3);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(390, 400, 97, 27));
        label_11 = new QLabel(page_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 40, 111, 17));
        btnCrear_3 = new QPushButton(page_3);
        btnCrear_3->setObjectName(QString::fromUtf8("btnCrear_3"));
        btnCrear_3->setGeometry(QRect(50, 430, 71, 27));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_25 = new QLabel(page_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(30, 100, 81, 17));
        label_26 = new QLabel(page_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(30, 130, 67, 17));
        label_28 = new QLabel(page_4);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(30, 160, 67, 17));
        label_29 = new QLabel(page_4);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(30, 190, 67, 17));
        label_30 = new QLabel(page_4);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(30, 40, 67, 17));
        lineEdit1 = new QLineEdit(page_4);
        lineEdit1->setObjectName(QString::fromUtf8("lineEdit1"));
        lineEdit1->setGeometry(QRect(120, 90, 113, 27));
        lineEdit2 = new QLineEdit(page_4);
        lineEdit2->setObjectName(QString::fromUtf8("lineEdit2"));
        lineEdit2->setGeometry(QRect(120, 120, 113, 27));
        lineEdit3 = new QLineEdit(page_4);
        lineEdit3->setObjectName(QString::fromUtf8("lineEdit3"));
        lineEdit3->setGeometry(QRect(120, 150, 113, 27));
        lineEdit4 = new QLineEdit(page_4);
        lineEdit4->setObjectName(QString::fromUtf8("lineEdit4"));
        lineEdit4->setGeometry(QRect(120, 180, 113, 27));
        label_27 = new QLabel(page_4);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(30, 220, 67, 17));
        pushButton_4 = new QPushButton(page_4);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(130, 340, 97, 27));
        checkBox_3 = new QCheckBox(page_4);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(430, 90, 97, 22));
        checkBox_4 = new QCheckBox(page_4);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(430, 120, 97, 22));
        checkBox_5 = new QCheckBox(page_4);
        checkBox_5->setObjectName(QString::fromUtf8("checkBox_5"));
        checkBox_5->setGeometry(QRect(430, 150, 97, 22));
        checkBox_6 = new QCheckBox(page_4);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(430, 180, 97, 22));
        checkBox_7 = new QCheckBox(page_4);
        checkBox_7->setObjectName(QString::fromUtf8("checkBox_7"));
        checkBox_7->setGeometry(QRect(430, 220, 97, 22));
        btnCrear_4 = new QPushButton(page_4);
        btnCrear_4->setObjectName(QString::fromUtf8("btnCrear_4"));
        btnCrear_4->setGeometry(QRect(30, 400, 71, 27));
        lineEdit_5 = new QLineEdit(page_4);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(120, 290, 113, 27));
        label_41 = new QLabel(page_4);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(50, 300, 67, 17));
        lineEdit5 = new QLineEdit(page_4);
        lineEdit5->setObjectName(QString::fromUtf8("lineEdit5"));
        lineEdit5->setGeometry(QRect(120, 210, 113, 27));
        lineEditMD = new QLineEdit(page_4);
        lineEditMD->setObjectName(QString::fromUtf8("lineEditMD"));
        lineEditMD->setGeometry(QRect(120, 260, 113, 27));
        label_43 = new QLabel(page_4);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(50, 270, 67, 17));
        stackedWidget->addWidget(page_4);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        btnCrear_5 = new QPushButton(page_6);
        btnCrear_5->setObjectName(QString::fromUtf8("btnCrear_5"));
        btnCrear_5->setGeometry(QRect(40, 450, 71, 27));
        pushButton_11 = new QPushButton(page_6);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(130, 400, 97, 27));
        label_33 = new QLabel(page_6);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(60, 40, 67, 17));
        lineEdit_6 = new QLineEdit(page_6);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(120, 310, 113, 27));
        lineEdit3_ = new QLineEdit(page_6);
        lineEdit3_->setObjectName(QString::fromUtf8("lineEdit3_"));
        lineEdit3_->setGeometry(QRect(120, 140, 113, 27));
        label_34 = new QLabel(page_6);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(30, 210, 67, 17));
        checkBox_8 = new QCheckBox(page_6);
        checkBox_8->setObjectName(QString::fromUtf8("checkBox_8"));
        checkBox_8->setGeometry(QRect(430, 80, 97, 22));
        checkBox_9 = new QCheckBox(page_6);
        checkBox_9->setObjectName(QString::fromUtf8("checkBox_9"));
        checkBox_9->setGeometry(QRect(430, 110, 97, 22));
        lineEdit2_ = new QLineEdit(page_6);
        lineEdit2_->setObjectName(QString::fromUtf8("lineEdit2_"));
        lineEdit2_->setGeometry(QRect(120, 110, 113, 27));
        lineEdit1_ = new QLineEdit(page_6);
        lineEdit1_->setObjectName(QString::fromUtf8("lineEdit1_"));
        lineEdit1_->setGeometry(QRect(120, 80, 113, 27));
        checkBox_10 = new QCheckBox(page_6);
        checkBox_10->setObjectName(QString::fromUtf8("checkBox_10"));
        checkBox_10->setGeometry(QRect(430, 140, 97, 22));
        label_35 = new QLabel(page_6);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(30, 150, 67, 17));
        label_36 = new QLabel(page_6);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(30, 120, 67, 17));
        label_37 = new QLabel(page_6);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(30, 180, 67, 17));
        lineEdit4_ = new QLineEdit(page_6);
        lineEdit4_->setObjectName(QString::fromUtf8("lineEdit4_"));
        lineEdit4_->setGeometry(QRect(120, 170, 113, 27));
        checkBox_11 = new QCheckBox(page_6);
        checkBox_11->setObjectName(QString::fromUtf8("checkBox_11"));
        checkBox_11->setGeometry(QRect(430, 170, 97, 22));
        label_38 = new QLabel(page_6);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(30, 90, 81, 17));
        checkBox_12 = new QCheckBox(page_6);
        checkBox_12->setObjectName(QString::fromUtf8("checkBox_12"));
        checkBox_12->setGeometry(QRect(430, 200, 97, 22));
        lineEdit_11 = new QLineEdit(page_6);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(120, 350, 113, 27));
        label_39 = new QLabel(page_6);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(50, 320, 67, 17));
        label_40 = new QLabel(page_6);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(50, 360, 67, 17));
        lineEdit_12 = new QLineEdit(page_6);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(120, 270, 113, 27));
        label_42 = new QLabel(page_6);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(50, 280, 67, 17));
        lineEdit5_ = new QLineEdit(page_6);
        lineEdit5_->setObjectName(QString::fromUtf8("lineEdit5_"));
        lineEdit5_->setGeometry(QRect(120, 200, 113, 27));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        label_91 = new QLabel(page_7);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(20, 70, 81, 17));
        _lineEdit2 = new QLineEdit(page_7);
        _lineEdit2->setObjectName(QString::fromUtf8("_lineEdit2"));
        _lineEdit2->setGeometry(QRect(110, 90, 113, 27));
        label_92 = new QLabel(page_7);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(20, 190, 67, 17));
        label_93 = new QLabel(page_7);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(40, 300, 67, 17));
        label_94 = new QLabel(page_7);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(20, 130, 67, 17));
        btnCrear_16 = new QPushButton(page_7);
        btnCrear_16->setObjectName(QString::fromUtf8("btnCrear_16"));
        btnCrear_16->setGeometry(QRect(30, 430, 71, 27));
        label_95 = new QLabel(page_7);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(40, 340, 67, 17));
        _lineEdit4 = new QLineEdit(page_7);
        _lineEdit4->setObjectName(QString::fromUtf8("_lineEdit4"));
        _lineEdit4->setGeometry(QRect(110, 150, 113, 27));
        checkBox_39 = new QCheckBox(page_7);
        checkBox_39->setObjectName(QString::fromUtf8("checkBox_39"));
        checkBox_39->setGeometry(QRect(420, 90, 97, 22));
        label_96 = new QLabel(page_7);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(20, 160, 67, 17));
        checkBox_40 = new QCheckBox(page_7);
        checkBox_40->setObjectName(QString::fromUtf8("checkBox_40"));
        checkBox_40->setGeometry(QRect(420, 120, 97, 22));
        label_97 = new QLabel(page_7);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(20, 100, 67, 17));
        _lineEdit1 = new QLineEdit(page_7);
        _lineEdit1->setObjectName(QString::fromUtf8("_lineEdit1"));
        _lineEdit1->setGeometry(QRect(110, 60, 113, 27));
        lineEdit_46 = new QLineEdit(page_7);
        lineEdit_46->setObjectName(QString::fromUtf8("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(110, 330, 113, 27));
        _lineEdit3 = new QLineEdit(page_7);
        _lineEdit3->setObjectName(QString::fromUtf8("_lineEdit3"));
        _lineEdit3->setGeometry(QRect(110, 120, 113, 27));
        pushButton_34 = new QPushButton(page_7);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(120, 380, 97, 27));
        checkBox_38 = new QCheckBox(page_7);
        checkBox_38->setObjectName(QString::fromUtf8("checkBox_38"));
        checkBox_38->setGeometry(QRect(420, 60, 97, 22));
        label_98 = new QLabel(page_7);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(50, 20, 67, 17));
        checkBox_41 = new QCheckBox(page_7);
        checkBox_41->setObjectName(QString::fromUtf8("checkBox_41"));
        checkBox_41->setGeometry(QRect(420, 150, 97, 22));
        lineEdit_45 = new QLineEdit(page_7);
        lineEdit_45->setObjectName(QString::fromUtf8("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(110, 290, 113, 27));
        checkBox_42 = new QCheckBox(page_7);
        checkBox_42->setObjectName(QString::fromUtf8("checkBox_42"));
        checkBox_42->setGeometry(QRect(420, 180, 97, 22));
        _lineEdit5 = new QLineEdit(page_7);
        _lineEdit5->setObjectName(QString::fromUtf8("_lineEdit5"));
        _lineEdit5->setGeometry(QRect(110, 180, 113, 27));
        lineEdit_13 = new QLineEdit(page_7);
        lineEdit_13->setObjectName(QString::fromUtf8("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(110, 250, 113, 27));
        label_44 = new QLabel(page_7);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(40, 260, 67, 17));
        stackedWidget->addWidget(page_7);
        page_20 = new QWidget();
        page_20->setObjectName(QString::fromUtf8("page_20"));
        lineEdit_105 = new QLineEdit(page_20);
        lineEdit_105->setObjectName(QString::fromUtf8("lineEdit_105"));
        lineEdit_105->setGeometry(QRect(140, 140, 113, 27));
        label_205 = new QLabel(page_20);
        label_205->setObjectName(QString::fromUtf8("label_205"));
        label_205->setGeometry(QRect(70, 110, 67, 17));
        lineEdit_106 = new QLineEdit(page_20);
        lineEdit_106->setObjectName(QString::fromUtf8("lineEdit_106"));
        lineEdit_106->setGeometry(QRect(140, 100, 113, 27));
        label_206 = new QLabel(page_20);
        label_206->setObjectName(QString::fromUtf8("label_206"));
        label_206->setGeometry(QRect(70, 150, 67, 17));
        label_207 = new QLabel(page_20);
        label_207->setObjectName(QString::fromUtf8("label_207"));
        label_207->setGeometry(QRect(70, 40, 67, 17));
        btnCrear_35 = new QPushButton(page_20);
        btnCrear_35->setObjectName(QString::fromUtf8("btnCrear_35"));
        btnCrear_35->setGeometry(QRect(60, 240, 71, 27));
        pushButton_71 = new QPushButton(page_20);
        pushButton_71->setObjectName(QString::fromUtf8("pushButton_71"));
        pushButton_71->setGeometry(QRect(150, 190, 97, 27));
        stackedWidget->addWidget(page_20);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 784, 25));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("MainWindow", "Select", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("MainWindow", "Delete", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("MainWindow", "Update", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("MainWindow", "Insert", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("MainWindow", "Crear Tabla", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("MainWindow", "Crear Tablespace", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Create TableSpace", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Nombre BD", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Version DB", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Contrase\303\261a BD", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Cantidad Bloques", 0, QApplication::UnicodeUTF8));
        btnCrear->setText(QApplication::translate("MainWindow", "Crear TableSpace", 0, QApplication::UnicodeUTF8));
        btnCrear_2->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Nombre Tabla", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("MainWindow", "Add Campos", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "Cantidad Campos", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Tipo campo", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Nombre Campo", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Size (Varchar y Char)", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Default", 0, QApplication::UnicodeUTF8));
        chkNull->setText(QApplication::translate("MainWindow", "Null", 0, QApplication::UnicodeUTF8));
        chkPK->setText(QApplication::translate("MainWindow", "PK", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("MainWindow", "Agregar", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("MainWindow", "Crear Tabla", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "Crear Tabla", 0, QApplication::UnicodeUTF8));
        btnCrear_3->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "Int", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "Double", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "Char", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "Varchar", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "INSERT", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "Boolean", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("MainWindow", "Insertar", 0, QApplication::UnicodeUTF8));
        checkBox_3->setText(QString());
        checkBox_4->setText(QString());
        checkBox_5->setText(QString());
        checkBox_6->setText(QString());
        checkBox_7->setText(QString());
        btnCrear_4->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("MainWindow", "BlockID", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("MainWindow", "MD", 0, QApplication::UnicodeUTF8));
        btnCrear_5->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        pushButton_11->setText(QApplication::translate("MainWindow", "Select", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("MainWindow", "SELECT", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindow", "Boolean", 0, QApplication::UnicodeUTF8));
        checkBox_8->setText(QString());
        checkBox_9->setText(QString());
        checkBox_10->setText(QString());
        label_35->setText(QApplication::translate("MainWindow", "Char", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "Double", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindow", "Varchar", 0, QApplication::UnicodeUTF8));
        checkBox_11->setText(QString());
        label_38->setText(QApplication::translate("MainWindow", "Int", 0, QApplication::UnicodeUTF8));
        checkBox_12->setText(QString());
        label_39->setText(QApplication::translate("MainWindow", "BlockID", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindow", "Index", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("MainWindow", "MD", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("MainWindow", "Int", 0, QApplication::UnicodeUTF8));
        label_92->setText(QApplication::translate("MainWindow", "Boolean", 0, QApplication::UnicodeUTF8));
        label_93->setText(QApplication::translate("MainWindow", "BlockID", 0, QApplication::UnicodeUTF8));
        label_94->setText(QApplication::translate("MainWindow", "Char", 0, QApplication::UnicodeUTF8));
        btnCrear_16->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        label_95->setText(QApplication::translate("MainWindow", "Index", 0, QApplication::UnicodeUTF8));
        checkBox_39->setText(QString());
        label_96->setText(QApplication::translate("MainWindow", "Varchar", 0, QApplication::UnicodeUTF8));
        checkBox_40->setText(QString());
        label_97->setText(QApplication::translate("MainWindow", "Double", 0, QApplication::UnicodeUTF8));
        pushButton_34->setText(QApplication::translate("MainWindow", "Update", 0, QApplication::UnicodeUTF8));
        checkBox_38->setText(QString());
        label_98->setText(QApplication::translate("MainWindow", "UPDATE", 0, QApplication::UnicodeUTF8));
        checkBox_41->setText(QString());
        checkBox_42->setText(QString());
        label_44->setText(QApplication::translate("MainWindow", "MD", 0, QApplication::UnicodeUTF8));
        label_205->setText(QApplication::translate("MainWindow", "BlockID", 0, QApplication::UnicodeUTF8));
        label_206->setText(QApplication::translate("MainWindow", "Index", 0, QApplication::UnicodeUTF8));
        label_207->setText(QApplication::translate("MainWindow", "DELETE", 0, QApplication::UnicodeUTF8));
        btnCrear_35->setText(QApplication::translate("MainWindow", "Volver", 0, QApplication::UnicodeUTF8));
        pushButton_71->setText(QApplication::translate("MainWindow", "Delete", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
